language: java

notifications:
  email: false

addons:
  sonarcloud:
    organization: "qrowsxi"
    token:
      secure: "IBT+bpzRPETKK6Rik4fejC/IECygcPsRt4A/gvgsJ8txLBJAt7qOgWMpxSyoilexcKrWXPhAsLUbxPof7yl65fwUlm3n3Ls8maDpw2cIW5iOncwcSx9WgCuuL4dN6uybwaQqc1zU5vVmTrqYn/xiJL666nf6+8njnJ3Pi3etDZHKPOl/b89Drp/Q1laqouy876rt7na4E/NDf22Pbfmq/xcgqxytwkGdX9NWFuJtWSpNMIZ5VPyTK+OEDo9KscQPAUhzBRSGP52X3CWiA5jktrb3jFYtSXqmeKt+TGKeTvDEdAG8Be2A0FkAddv4h5pUB/Mu8YMMuUI/qZpBH+MpLZrWx8ydcxGJlu5BQj7NP5aauIqM3uJUP3VhgXxutMpM5ILrG7nI+Dc3C7FfS1WtmO/YfOCE0xxY7wgurMJa1VoBT0NUhkcekYJTS94j3VIRDgnHu+v820RbPyL1onOoU7gkZ1ZrvSnK9No03bV2nezQ0jxaYC6X9e1JIZAZ1WRu6kz/xUBG5PwYMETxD9RcUOUEnheMBPPq5eEKup8GVk5+zpUkcanv5tDJBygM7u+CLygSKHQ1z7wlh4ljcyUsgtcZ7SwmJwUQQqn8EdDRX19ycg76e0XL523l9YVTDlke8dxWuCNSeVIR/IR7nuHjE/+mu68MdxJyqpPz7EmMzXE="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=christiansantapaola_bookkeeper
